### ISSUE TITLE
Fiori elements application allows add itself to role in launchpad but not to group

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/sap-tech-bytes#2]
Hi @IObert 

Thank you for this post and the video, I was testing the MTA approach to build and deploy a fiori elements application in launchpad service and everything worked well, but when I tried to create a fiori elements app without a multimodule application, I mean just the application (with managed app router), everything but the aggregation of the app to a group in launchpad is working, do you know if this is an known issue or I'm making some mistake. I could add the application to the role but not to the group.

![image](https://user-images.githubusercontent.com/10300948/115723732-e2519380-a345-11eb-8258-607ced149783.png)

![image](https://user-images.githubusercontent.com/10300948/115723858-00b78f00-a346-11eb-9146-2289eb07dcdb.png)

![image](https://user-images.githubusercontent.com/10300948/115724115-45432a80-a346-11eb-90ab-b72e29349a74.png)

May be it could be some trial limitation I have some apps yet deployed there with other techniques, it's the first time with this approach (zero or low code hehe).

Kind regards.

Jhon Jairo.

**Comment by jhonj98** [comment]
Hi Marius,

It's the first time I see this problem, and if I follow a tutorial, no, I just create a Fiori elements application using the wizard in business application studio, the app is based on this tutorial https://github.com/SAP-samples/sap-devtoberfest-2020/blob/master/topics/appstudio/exercises/02.md, I just took the odata service info from this tutorial.

![image](https://user-images.githubusercontent.com/10300948/115870816-6585ee80-a405-11eb-9b21-aa320215f28a.png)

Today the odata service name is ZSEPMRA_PROD_MAN not SEPMRA_PROD_MAN, it's the only difference I see with respect to the odata service, the app is List report page of products, the app works well when executed from BAS.

Tell me if you need a detailed step by step for me to take the screenshots.

Thanks.

Jhon Jairo.

**Comment by IObert** [comment]
I just tested it and it works for me. Can you make sure that you have a similar section in your mainfest?
```
  "crossNavigation": {
            "inbounds": {
                "space-module1-inbound": {
                    "signature": {
                        "parameters": {},
                        "additionalParameters": "allowed"
                    },
                    "semanticObject": "semob",
                    "action": "show",
                    "title": "Hallo",
                    "subTitle": "",
                    "icon": ""
                }
            }
        }
```

It won't work if this section is missing.

**Comment by jhonj98** [comment]
Hi Marious,

I did that change and the issue is still happening.

![image](https://user-images.githubusercontent.com/10300948/116270509-c6cefa00-a744-11eb-9219-b9051585762c.png)

I did the change, built again, redeployed and refreshed the content provider.

![image](https://user-images.githubusercontent.com/10300948/116270123-6f308e80-a744-11eb-9da9-13679761e6a3.png)

Should I retry the scenario from scratch and put the crossnavigation part before building and deploying?

Regards.

Jhon Jairo.

**Comment by IObert** [comment]
Did you refresh the content of the HTML5 repo (this can be done in the Admin UI of the Launchpad service)

**Comment by jhonj98** [comment]
Yes Marious, I did it.

**Comment by IObert** [comment]
Strange. That should have done the trick. I'd recommend the fully remove the app then and to redeploy it with the updated manifest.

**Comment by jhonj98** [comment]
Hi Marious, I think it was some delay in refreshing the HTML5 repo, today I tried again to see if the app appeared when adding it to a group, and yes!, I could see it and add it to the group.

![image](https://user-images.githubusercontent.com/10300948/116565705-b85f1a80-a8cb-11eb-8101-6dda77b25259.png)

I just have a question, was this an issue in the fiori elements app generator? when someone creates an app individually and no in a multimodule project? I say this because with an fiori app inside a multimodule project I didn't have that issue.

Thank you very much for your support.

Jhon Jairo.

**Comment by IObert** [comment]
I guess that you didn't select the "Fiori Configuration" toggle button when you created the project (the default setting is "no"). This would explain why the configuration was missing in this project.

But maybe this was a bug that has been resolved now.

**Comment by jhonj98** [comment]
Thanks Marious!
