### ISSUE TITLE
Issue with multi module fiori project

### ISSUE THREAD

**Issue by AbhayGupta101** [SAP-samples/sap-tech-bytes#23]
Tutorial Link: https://github.com/SAP-samples/sap-tech-bytes/tree/2021-02-17-multi-module-fiori-project
 
Hi @IObert 
We are trying to achieve same situation where we have to consume XSUAA protected CAP service. We have created destination as mentioned in tutorial however somehow while accessing oData service url using Fiori tool, it is giving 500 error.

![image](https://user-images.githubusercontent.com/91308352/220278301-9e001078-618e-4f07-ae59-a2dca151331c.png)

Can you please also help with used backend service project so that i can check if there is mismatch or guide to find issue as there is no log available.

**Comment by jung-thomas** [comment]
The author of this particular content no longer works at SAP. I would suggest that you post your question with complete details in the SAP Community Q&A
