### ISSUE TITLE
Switch btp logins ?

### ISSUE THREAD

**Issue by srinivas2210** [SAP-samples/sap-tech-bytes#8]
Hello @qmacro  - Thanks for the blog post and the Friday's session. I was wondering as to how we can switch the btp logins between different trial accounts when the config file holds a default value. I tried to use --sso with the login and then it defaults the subdomain ( of course ) which is not good to switch. Then I wondered if I can have multiple config files named as per my convenience and the btp cli gives me the option to choose one of the files to load the credentials. I guess that is not there yet. 
Any thoughts ?

**Comment by qmacro** [comment]
Hey @srinivas2210 thanks for the great question. In fact, I'd been wondering about this too. There's nothing that is directly supported yet in the btp CLI itself, but I have a home-grown solution that I use; perhaps it's worth sharing that on an upcoming live stream - what do you think? If you want a quick look beforehand, have a look in the `btp` directory in my dotfiles: https://github.com/qmacro/dotfiles/tree/main/scripts/btp. Hope that helps for now!
